twig:
    default_path: "%kernel.project_dir%/templates"
    globals:
        contact_address: "12 rue du Village"
        contact_zip: "01000"
        contact_city: "Ville"
        contact_phone: "01 23 45 67 89"
        contact_email: "prenom.nom@domaine.fr"

when@test:
    twig:
        strict_variables: true
